# Copyright 2026 AlphaAvatar project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Transport-independent, time-aligned output events."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any


class OutputLane(StrEnum):
    """Logical output lanes, independent of transport."""

    ASSISTANT = "assistant"
    TRANSIENT = "transient"
    STATUS = "status"
    CHARACTER = "character"


class OutputKind(StrEnum):
    STATUS = "status"

    # Source message text generated by an LLM, plugin or application.
    TEXT_CHUNK = "text_chunk"

    AUDIO_FRAME = "audio_frame"

    ALIGNMENT = "alignment"

    # Feedback from the transport audio output.
    PLAYBACK = "playback"

    # Text confirmed as delivered according to actual audio playout.
    TRANSCRIPT_CHUNK = "transcript_chunk"

    CONTROL = "control"


class OutputTextMode(StrEnum):
    """
    How source text participates in user-visible delivery.

    MIRROR:
        Retained for timeline and observability only. Another system owns
        delivery, such as LiveKit AgentSession during the migration period.

    IMMEDIATE:
        Text may be delivered immediately without waiting for audio.

    AUDIO_SYNCED:
        Text must become visible only through synchronized transcript events.
    """

    MIRROR = "mirror"
    IMMEDIATE = "immediate"
    AUDIO_SYNCED = "audio_synced"


class OutputControlType(StrEnum):
    INTERRUPT = "interrupt"

    # The source/producer will not publish more text or audio. Transport
    # playout may still be draining queued audio.
    COMPLETE = "complete"


class OutputPlaybackType(StrEnum):
    STARTED = "started"
    PROGRESS = "progress"
    FINISHED = "finished"
    INTERRUPTED = "interrupted"


@dataclass(frozen=True, slots=True)
class OutputTextChunk:
    text: str
    chunk_id: str
    is_first: bool
    is_final: bool
    mode: OutputTextMode = OutputTextMode.MIRROR


@dataclass(frozen=True, slots=True)
class OutputTranscriptChunk:
    """
    User-visible text aligned with actual audio playout.

    source_chunk_id links this transcript piece back to the original source
    text chunk. Timing is relative to the beginning of the logical output.
    """

    text: str
    chunk_id: str
    source_chunk_id: str | None
    start_time_sec: float | None
    end_time_sec: float | None
    is_first: bool
    is_final: bool
    interrupted: bool = False


@dataclass(frozen=True, slots=True)
class OutputTextAudioAlignment:
    """
    Map one source-text chunk to its generated audio interval.

    Timing is relative to the beginning of the logical output identified by
    output_id.
    """

    text: str
    source_chunk_id: str
    start_time_sec: float
    end_time_sec: float
    is_final: bool
    partial: bool = False
    timing_source: str = "synthesized_audio"

    @property
    def duration_sec(self) -> float:
        return max(self.end_time_sec - self.start_time_sec, 0.0)


@dataclass(frozen=True, slots=True)
class OutputPlayback:
    """Transport-reported audio playout state."""

    type: OutputPlaybackType
    played_duration_sec: float
    pushed_duration_sec: float
    queued_duration_sec: float


@dataclass(frozen=True, slots=True)
class OutputControl:
    type: OutputControlType
    reason: str
    target_lane: OutputLane | None = None
    target_output_id: str | None = None
    target_turn_id: str | None = None


@dataclass(frozen=True, slots=True)
class OutputEvent:
    """
    One item on the session output timeline.

    sequence provides total ordering across status, source text, audio frames,
    playback feedback, delivered transcripts and control events.
    """

    event_id: str
    sequence: int
    session_id: str
    created_at: float
    monotonic_ns: int
    kind: OutputKind
    lane: OutputLane
    output_id: str | None = None
    turn_id: str | None = None
    payload: Any = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def is_control(self) -> bool:
        return self.kind == OutputKind.CONTROL
