# Copyright 2026 AlphaAvatar project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from typing import Any

from pydantic import BaseModel, Field


class ProviderUsage(BaseModel):
    """
    Normalized token/cost usage for AlphaAvatar provider calls.

    Naming rule:
    - input_*: tokens consumed by model input/context.
    - output_*: tokens generated by model output.
    - *_tokens_raw fields from providers should be preserved in `raw`.
    """

    # Normalized AlphaAvatar fields
    input_tokens: int | None = None
    output_tokens: int | None = None
    total_tokens: int | None = None

    # Cache accounting
    # Tokens read from provider-side prompt/context cache.
    cache_read_input_tokens: int | None = None

    # Tokens written/created into provider-side prompt/context cache.
    cache_write_input_tokens: int | None = None

    # Convenience field: normally read + write if both exist.
    cached_input_tokens: int | None = None

    # Non-cached input tokens, if provider exposes it or we can infer it.
    uncached_input_tokens: int | None = None

    # Reasoning / thinking tokens.
    # Usually charged as output by many providers, but still useful to track separately.
    reasoning_output_tokens: int | None = None

    # Tool/server-side token accounting.
    tool_input_tokens: int | None = None
    tool_output_tokens: int | None = None

    # Multimodal input token breakdown.
    text_input_tokens: int | None = None
    image_input_tokens: int | None = None
    audio_input_tokens: int | None = None
    video_input_tokens: int | None = None

    # Multimodal output token breakdown.
    text_output_tokens: int | None = None
    audio_output_tokens: int | None = None
    image_output_tokens: int | None = None
    video_output_tokens: int | None = None

    # Money / billing
    cost_usd: float | None = None

    # Provider-native usage object, kept for debugging and future migration.
    raw: dict[str, Any] = Field(default_factory=dict)

    # Any additional normalized-but-not-yet-standardized fields.
    extra: dict[str, Any] = Field(default_factory=dict)
