[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "alpha-avatar-plugins-router"
dynamic = ["version"]
description = "AlphaAvatar Framework plugin for realtime multimodal interaction routing"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11,<3.12"
keywords = [
    "omni",
    "realtime",
    "multimodal",
    "interaction",
    "router",
    "speech",
    "stt",
    "vad",
    "agents",
    "AI",
]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Multimedia :: Video",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "sherpa-onnx==1.13.6",
    "sherpa-onnx-core==1.13.6",
    "pypinyin",
    "sentencepiece",
]

[project.optional-dependencies]

[project.urls]
Source = "https://github.com/AlphaAvatar/AlphaAvatar"

[tool.hatch.version]
path = "alphaavatar/plugins/router/version.py"

[tool.hatch.build.targets.wheel]
packages = ["alphaavatar"]

[tool.hatch.build.targets.sdist]
include = [
    "alphaavatar",
    "README.md",
    "LICENSE",
]
